"""Added previous session table

Revision ID: 47f6ee7c3952
Revises: 
Create Date: 2024-02-06 23:35:22.340666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f6ee7c3952'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previous_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('slides', sa.String(), nullable=True),
    sa.Column('recording', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('chat_log', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('thumbnails', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('previous_sessions')
    # ### end Alembic commands ###
