"""Added sprint session table

Revision ID: f78a19de946d
Revises: 0bf8a887955e
Create Date: 2024-03-02 09:36:26.313948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78a19de946d'
down_revision: Union[str, None] = '0bf8a887955e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slides', sa.String(), nullable=True),
    sa.Column('recording', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('chat_log', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('thumbnails', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprint_session')
    # ### end Alembic commands ###
