domain: masterclasses.canonical.com

image: prod-comms.ps5.docker-registry.canonical.com/masterclasses.canonical.com

env:
  - name: SENTRY_DSN
    value: https://ac1f05d48419453ab98e9af52d0da6ae@sentry.is.canonical.com//35

  - name: PRIVATE_KEY_ID
    secretKeyRef:
      key: private-key-id
      name: masterclasses-canonical-com

  - name: PRIVATE_KEY
    secretKeyRef:
      key: private-key
      name: masterclasses-canonical-com

  - name: DATABASE_URL
    secretKeyRef:
      key: masterclasses-database-url
      name: masterclasses-canonical-com

# Overrides for production
production:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 2
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
  tlsName: staging-masterclasses-canonical-com-tls
  domain: staging.masterclasses.canonical.com

# Overrides for demo
demo:
  env:
    - name: OPENID_LAUNCHPAD_TEAM
      value: canonical-content-people
    - name: FLASK_DEBUG
      value: true
    - name: API_TOKEN
      value: super-secret-token
